--
-- PostgreSQL database dump
--

-- Dumped from database version 10.23
-- Dumped by pg_dump version 13.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(255),
    price bigint DEFAULT 0.00,
    img_url character varying(255),
    description character varying(255)
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_carts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_carts (
    id integer NOT NULL,
    created_at character varying(255),
    user_id integer NOT NULL,
    subtotal real DEFAULT 0.00,
    total double precision DEFAULT 0.00
);


ALTER TABLE public.shop_carts OWNER TO postgres;

--
-- Name: shop_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_carts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.shop_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_cart_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_cart_products (
    id integer NOT NULL,
    product_id integer NOT NULL,
    shop_cart_id integer NOT NULL,
    amount double precision DEFAULT 0.00,
    quantity integer DEFAULT 1
);


ALTER TABLE public.shop_cart_products OWNER TO postgres;

--
-- Name: shop_cart_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_cart_products ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.shop_cart_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, price, img_url, description) FROM stdin;
1	Product 1	15	http://someurl.com/image	Product 1 description
2	Product 2	15	http://someurl.com/image	Product 2 description
\.


--
-- Data for Name: shop_cart_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_cart_products (id, product_id, shop_cart_id, amount, quantity) FROM stdin;
\.


--
-- Data for Name: shop_carts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_carts (id, created_at, user_id, subtotal, total) FROM stdin;
12	"2016-11-02"	1	30	30
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, password) FROM stdin;
1	carlos	12345
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 2, true);


--
-- Name: shop_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_cart_id_seq', 12, true);


--
-- Name: shop_cart_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_cart_products_id_seq', 4, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 1, true);


--
-- Name: products product_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT product_pk PRIMARY KEY (id);


--
-- Name: shop_carts shop_cart_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_carts
    ADD CONSTRAINT shop_cart_pk PRIMARY KEY (id);


--
-- Name: shop_cart_products shop_cart_products_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_cart_products
    ADD CONSTRAINT shop_cart_products_pk PRIMARY KEY (id);


--
-- Name: users user_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_pk PRIMARY KEY (id);


--
-- Name: shop_cart_products shop_cart_products_product_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_cart_products
    ADD CONSTRAINT shop_cart_products_product_id_fk FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: shop_cart_products shop_cart_products_shop_cart_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_cart_products
    ADD CONSTRAINT shop_cart_products_shop_cart_id_fk FOREIGN KEY (shop_cart_id) REFERENCES public.shop_carts(id);


--
-- Name: shop_carts shop_cart_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_carts
    ADD CONSTRAINT shop_cart_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

